version: '3'
services:

  mysql:
    container_name: mysql-container
    image: mysql:5.7
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: quizzApp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  login-service:
    container_name: login-container
    restart: always
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mysql