global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.5.188:8091']        
  - job_name: 'spring_boot_actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.5.188:9092', '10.0.5.188:9090', '10.0.5.188:9095', '10.0.5.188:9091']
