version: '3'

services:
  springboot:
    build: .
    restart: always
    container_name: spring-mongo-app-container
    ports:
      - 8088:8080
#    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo-container
    ports:  # for demo/debug purpose only
      - 27000:27017
   volumes:
      - $HOME/data/springboot-mongo-data:/data/db
 
    restart: always
