#kafka:
#  bootstrap-servers: 172.23.238.156:9092
#spring:
#    jpa:
#        database: MYSQL
#        hibernate:
#            ddl-auto: validate
#
#    datasource:
#        url: jdbc:mysql://mysql:3306/tsbacked
#        username: root
#        password: 12345
#        driver-class-name: com.mysql.jdbc.Driver