version: '3'
services: 
  springboot:
    build: .
    image: adaptivegame
    restart: always
    container_name: adaptive
    ports:
      - 8081:8081
    depends_on:
      - neo4j
    network_mode: "host"
    hostname: localhost

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    #   - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes      
    #   - NEO4J_causalClustering_expectedCoreClusterSize=3
    #   - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
    #   - NEO4J_dbms_connector_http_listen__address=:7474
    #   - NEO4J_dbms_connector_https_listen__address=:6477
    #   - NEO4J_dbms_connector_bolt_listen__address=:7687
    volumes:
      - $HOME/var/lib/neo4j/data:/data
    network_mode: "host"
    hostname: localhost
